### ISSUE TITLE
404 Store Link

### ISSUE THREAD

**Issue by d4rkd0s** [frantic/clippy#1]
The store link goes to a 404
https://chrome.google.com/webstore/detail/dmkmjgjfijaipdmckipknjllojnmebgo

**Comment by caburum** [comment]
Yeah, you could try manually packing it via the Chrome Extensions page. See [https://support.google.com/chrome/a/answer/2714278](https://support.google.com/chrome/a/answer/2714278).

**Comment by d4rkd0s** [comment]
@CCreativeCND gotcha
